version: '3'
services:
  web1:
    image: nginx:alpine
    container_name: web1
    volumes:
      - ./web1:/usr/share/nginx/html
    networks:
      - backend

  web2:
    image: nginx:alpine
    container_name: web2
    volumes:
      - ./web2:/usr/share/nginx/html
    networks:
      - backend

  web3:
    image: nginx:alpine
    container_name: web3
    volumes:
      - ./web3:/usr/share/nginx/html
    networks:
      - backend

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/ssl
    depends_on:
      - web1
      - web2
      - web3
    networks:
      - backend

networks:
  backend:
    driver: bridge
