services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./ssl:/etc/letsencrypt/live/ct519-463.ck2all.com
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - nginx-network

  # letsencrypt-nginx-proxy-companion:
  #   image: nginxproxy/acme-companion
  #   container_name: letsencrypt-nginx-proxy-companion
  #   volumes:
  #     - ./nginx/certs:/etc/nginx/certs
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   environment:
  #     - NGINX_PROXY_CONTAINER=nginx-proxy
  #   networks:
  #     - nginx-network

  web1:
    build: ./web1
    environment:
      - VIRTUAL_HOST=ct519-463.ck2all.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=ct519-463.ck2all.com
      - LETSENCRYPT_EMAIL=pornsupat1356@gmail.com
    networks:
      - nginx-network

  web2:
    build: ./web2
    environment:
      - VIRTUAL_HOST=ct519-463.ck2all.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=ct519-463.ck2all.com
      - LETSENCRYPT_EMAIL=pornsupat1356@gmail.com
    networks:
      - nginx-network

  web3:
    build: ./web3
    environment:
      - VIRTUAL_HOST=ct519-463.ck2all.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=ct519-463.ck2all.com
      - LETSENCRYPT_EMAIL=pornsupat1356@gmail.com
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge