# Use the official Nginx image from Docker Hub
FROM nginx:alpine

# Copy the custom nginx.conf to the container
COPY nginx.conf /etc/nginx/nginx.conf

COPY certs /etc/letsencrypt/live/ct519-463.ck2all.com